name: Lucky Blocks
version: 1.0
description: Lucky Blocks entwickelt von Firei
author: Firei
main: li.angu.firei.luckyblocks.Main
softdepend: [HolographicDisplays]
commands:
  action:
    usage: /action [Aktion]
  save:
    usage: /save